spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/lozigorbox?useSSL=false&characterEncoding=UTF-8
    username: create_user
    password: create_user
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
logging:
  level:
    .: warn
    org.springframework.web: WARN
debug: false